version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: spirual/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: spirual/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: spirual/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - backend
      - frontend
