version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: spirual/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: spirual/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /app/result_build/
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: spirual/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
    depends_on:
      - backend
      - frontend
