# Generated by Django 3.2.23 on 2024-01-29 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1, message=('Количество ингридиентов не может быть меньше 1',))], verbose_name='Количество'),
        ),
    ]
