# Generated by Django 3.2.23 on 2024-02-02 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='shopping_list',
            field=models.ManyToManyField(blank=True, related_name='shopping_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
