# Generated by Django 3.2.23 on 2024-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_delete_shoppinglist'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shopping_list',
            field=models.ManyToManyField(related_name='added_to_shopping_list', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(related_name='added_to_favorites', to='recipes.Recipe'),
        ),
    ]
