# Generated by Django 3.2.23 on 2024-01-29 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Используются недопустимые символы в имени пользователя', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
