# Generated by Django 3.2.23 on 2024-02-01 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240201_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribes',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
