# Generated by Django 3.2.23 on 2024-02-01 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_delete_subscription'),
        ('users', '0003_customuser_subscribes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='added_to_favorites', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shopping_list',
            field=models.ManyToManyField(blank=True, related_name='added_to_shopping_list', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
