# Generated by Django 3.2.23 on 2024-02-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240201_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shopping_list',
        ),
    ]
