# Generated by Django 3.2.23 on 2024-02-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscribes',
        ),
    ]
